name: cinemapedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^2.0.4
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.2.0
  flutter_staggered_grid_view: ^0.6.2
  go_router: ^6.0.9
  intl: ^0.18.0
  youtube_player_flutter: ^8.1.2
  path: ^1.9.0
  path_provider: ^2.1.4
  sembast: ^3.7.5
  sembast_web: ^2.4.0+4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/loaders/
